[versions]
kotlin = "2.4.10"
spring-boot = "4.1.1"
spring-dependency-management = "1.1.7"
springdoc-openapi = "3.1.0"
springmockk = "5.0.1"

[libraries]
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-oauth2-client = { module = "org.springframework.boot:spring-boot-starter-oauth2-client" }
spring-boot-starter-log4j2 = { module = "org.springframework.boot:spring-boot-starter-log4j2" }
log4j-layout-template-json = { module = "org.apache.logging.log4j:log4j-layout-template-json" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc-openapi" }
spring-boot-restclient = { module = "org.springframework.boot:spring-boot-restclient" }
spring-boot-restclient-test = { module = "org.springframework.boot:spring-boot-restclient-test" }
spring-boot-resttestclient = { module = "org.springframework.boot:spring-boot-resttestclient" }
spring-boot-webmvc-test = { module = "org.springframework.boot:spring-boot-webmvc-test" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
springmockk = { module = "com.ninja-squad:springmockk", version.ref = "springmockk" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
