apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "pensjon-dokdist"
  namespace: "pensjonsbrev"
  labels:
    team: "pensjonsbrev"
spec:
  image: "{{{ image }}}"
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: "/api/internal/isAlive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/api/internal/isReady"
    port: 8080
    initialDelay: 20
    timeout: 60
  ingresses:
    - "https://pensjon-dokdist.intern.nav.no"
  azure:
    application:
      enabled: true
      replyURLs:
        - "https://pensjon-dokdist.intern.nav.no/login/oauth2/code/azure"
  env:
    - name: "SPRING_PROFILES_ACTIVE"
      value: "nais"
    - name: "DISTRIBUER_JOURNALPOST_URL"
      value: "https://dokdistfordeling.prod-fss-pub.nais.io"
    - name: "DISTRIBUER_JOURNALPOST_SCOPE"
      value: "api://prod-fss.teamdokumenthandtering.saf/.default"
    - name: "DOKARKIV_BASE_URL"
      value: "https://dokarkiv.prod-fss-pub.nais.io"
    - name: "DOKARKIV_SCOPE"
      value: "api://prod-fss.teamdokumenthandtering.dokarkiv/.default"
    - name: "SAF_GRAPHQL"
      value: "https://saf.prod-fss-pub.nais.io"
    - name: "SAF_GRAPHQL_SCOPE"
      value: "api://prod-fss.teamdokumenthandtering.saf/.default"
    - name: "BREVMETADATA_URL"
      value: "https://pensjon-brevmetadata.intern.nav.no"
