apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "pensjon-dokdist"
  namespace: "pensjonsbrev"
  labels:
    team: "pensjonsbrev"
spec:
  image: "{{{ image }}}"
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: "/api/internal/isAlive"
    initialDelay: 3
    timeout: 1
  readiness:
    path: "/api/internal/isReady"
    initialDelay: 3
    timeout: 1
  ingresses:
    - "https://pensjon-dokdist.prod-fss.nais.io"
    - "https://pensjon-dokdist.nais.adeo.no"
  vault:
    enabled: true
    paths:
      - kvPath: "credential/data/prod/oidc-openam-pensjon-dokdist"
        mountPath: "/secrets/oidc"
      - kvPath: "serviceuser/data/prod/srvpensjon-dokdist"
        mountPath: "/secrets/serviceuser"
  env:
    - name: "SECRET_BASEDIR"
      value: "/"
    - name: "OIDC_ISSUER_URI"
      value: "https://isso.adeo.no:443/isso/oauth2"
    - name: "OIDC_CLIENT_ID"
      value: "pensjon-dokdist-p"
    - name: "DISTRIBUER_JOURNALPOST_URL"
      value: "https://dokdistfordeling.intern.nav.no/rest/v1/distribuerjournalpost"
    - name: "DOKARKIV_BASE_URL"
      value: "https://dokarkiv.intern.nav.no"
    - name: "SAF_GRAPHQL"
      value: "https://saf.nais.adeo.no/graphql"
    - name: "STS_URL"
      value: "https://security-token-service.nais.adeo.no/rest/v1/sts/token?grant_type=client_credentials&scope=openid"
    - name: "OIDC_ISSUER_HOST"
      value: "https://isso.adeo.no/isso/oauth2"
    - name: "BREVMETADATA_URL"
      value: "https://pensjon-brevmetadata.intern.nav.no"
