apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "pensjon-dokdist"
  namespace: "pensjonsbrev"
  labels:
    team: "pensjonsbrev"
spec:
  image: "{{{ image }}}"
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: "/api/internal/isAlive"
    initialDelay: 3
    timeout: 1
  readiness:
    path: "/api/internal/isReady"
    initialDelay: 3
    timeout: 1
  ingresses:
    - "https://pensjon-dokdist.dev-fss.nais.io"
  vault:
    enabled: true
    paths:
      - kvPath: "credential/data/dev/oidc-openam-pensjon-dokdist-q2"
        mountPath: "/secrets/oidc"
      - kvPath: "serviceuser/data/dev/srvpensjon-dokdist"
        mountPath: "/secrets/serviceuser"
  env:
    - name: "SECRET_BASEDIR"
      value: "/"
    - name: "OIDC_ISSUER_URI"
      value: "https://isso-q.adeo.no:443/isso/oauth2"
    - name: "OIDC_CLIENT_ID"
      value: "pensjon-dokdist-q2"
    - name: "DISTRIBUER_JOURNALPOST_URL"
      value: "https://dokdistfordeling-q2.dev-fss.nais.io/rest/v1/distribuerjournalpost"
    - name: "DOKARKIV_BASE_URL"
      value: "https://dokarkiv-q2.nais.preprod.local"
    - name: "SAF_GRAPHQL"
      value: "https://saf-q2.nais.preprod.local/graphql"
    - name: "STS_URL"
      value: "https://security-token-service.nais.preprod.local/rest/v1/sts/token?grant_type=client_credentials&scope=openid"
    - name: "OIDC_ISSUER_HOST"
      value: "https://isso-q.adeo.no/isso/oauth2"
